- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure for Students (e0117a90-c0d0-49ab-8e8b-6e80fdf13035)'
    subscriptionId: 'e0117a90-c0d0-49ab-8e8b-6e80fdf13035'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AppPipeline'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/HansenCloudCompute/CloudProject/blob/master/VNet.json'
    deploymentMode: 'Incremental'